server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: NODO_Final
  datasource:
    url: jdbc:mariadb://210.211.101.27:5019/NODO_Final_CA
    username: root
    password: quiPIgINaBLe
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: Hikari-MariaDB
      maximum-pool-size: 10
      minimum-idle: 4
      connection-timeout: 30000
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB


  jpa:
    open-in-view: false
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
            BasicBinder: trace
      springframework:
        transaction: TRACE
        orm:
          jpa:
            JpaTransactionManager: TRACE
